# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MultiClipboard.ui'
#
# Created: Tue Dec 22 15:33:28 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 502)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(320, 200))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_delete_selected = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete_selected.sizePolicy().hasHeightForWidth())
        self.btn_delete_selected.setSizePolicy(sizePolicy)
        self.btn_delete_selected.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_delete_selected.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_delete_selected.setCheckable(False)
        self.btn_delete_selected.setObjectName("btn_delete_selected")
        self.gridLayout.addWidget(self.btn_delete_selected, 3, 1, 1, 1)
        self.clearButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 0))
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 3, 0, 1, 1)
        self.cb_table = QtGui.QTableView(self.centralwidget)
        self.cb_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.cb_table.setAlternatingRowColors(True)
        self.cb_table.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.cb_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.cb_table.setObjectName("cb_table")
        self.gridLayout.addWidget(self.cb_table, 2, 0, 1, 5)
        self.findLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.findLineEdit.setInputMask("")
        self.findLineEdit.setText("")
        self.findLineEdit.setObjectName("findLineEdit")
        self.gridLayout.addWidget(self.findLineEdit, 1, 0, 1, 5)
        self.alwaysOnTop_check = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alwaysOnTop_check.sizePolicy().hasHeightForWidth())
        self.alwaysOnTop_check.setSizePolicy(sizePolicy)
        self.alwaysOnTop_check.setObjectName("alwaysOnTop_check")
        self.gridLayout.addWidget(self.alwaysOnTop_check, 4, 0, 1, 5)
        self.btn_merge_selected = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_merge_selected.sizePolicy().hasHeightForWidth())
        self.btn_merge_selected.setSizePolicy(sizePolicy)
        self.btn_merge_selected.setObjectName("btn_merge_selected")
        self.gridLayout.addWidget(self.btn_merge_selected, 3, 2, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        self.menuBla = QtGui.QMenu(self.menubar)
        self.menuBla.setObjectName("menuBla")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionReload_properties = QtGui.QAction(MainWindow)
        self.actionReload_properties.setObjectName("actionReload_properties")
        self.actionClear_content = QtGui.QAction(MainWindow)
        self.actionClear_content.setObjectName("actionClear_content")
        self.actionLoad_list = QtGui.QAction(MainWindow)
        self.actionLoad_list.setObjectName("actionLoad_list")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDelete_selected_rows = QtGui.QAction(MainWindow)
        self.actionDelete_selected_rows.setObjectName("actionDelete_selected_rows")
        self.menuBla.addAction(self.actionReload_properties)
        self.menuBla.addSeparator()
        self.menuBla.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionClear_content)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuBla.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_delete_selected.setText(QtGui.QApplication.translate("MainWindow", "Delete selected", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.findLineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.findLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.alwaysOnTop_check.setText(QtGui.QApplication.translate("MainWindow", "Always on top", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_merge_selected.setText(QtGui.QApplication.translate("MainWindow", "Merge selected", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBla.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_properties.setText(QtGui.QApplication.translate("MainWindow", "Reload properties ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_content.setText(QtGui.QApplication.translate("MainWindow", "Clear content", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_list.setText(QtGui.QApplication.translate("MainWindow", "Load list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_selected_rows.setText(QtGui.QApplication.translate("MainWindow", "Delete selected rows", None, QtGui.QApplication.UnicodeUTF8))

